### ISSUE TITLE
Integration with angular-cli project

### ISSUE THREAD

**Issue by benzid-wael** [mistic100/jQuery-QueryBuilder#485]
I tried to integrate the plugin with an Angular 2 project built using angular-cli. I installed the npm package

```npm install jQuery-QueryBuilder```

Then I updated `angular-cli.json` file: I included css/js files into my project.

```json

   scripts: [
        "../node_modules/jquery/dist/jquery-min.js",
        "../node_modules/jQuery-QueryBuilder/dist/js/query-builder.standalone.js",
   ]
```

In my component, I have something like:

```javascript
import * as jQuery from 'jquery';

// initialize QueryBuilder
jQuery(this.queryBuilderElt.nativeElement).queryBuilder(myConfig)
```

The compilation is succedded, But on runtime I get this error: `queryBuilder is not a function`. I guess the problem could be that the plugin was not registered. So I tried to import and I added this line

```javascript
import * as jQuery from 'jquery';
import * as querybuilder from 'jQuery-Querybuilder'
// The below line does not work too
// import  'jQuery-Querybuilder'
```

and now the project is not event compiled. Did you have any example how to integrate the plugin with `angular-cli` project?

## Update

I changed my code to use the bundeled jQuery object

```javascript

declare var jQuery: any;
```

but when I initialize my component I got this error:

```javascript

s.(anonymous function) (http://localhost:4200/vendor.bundle.js:151765:25) undefinedr.Deferred.exceptionHook @ VM12812:2k @ VM12812:2ZoneDelegate.invokeTask @ zone.js:275onInvokeTask @ ng_zone.js:260ZoneDelegate.invokeTask @ zone.js:274Zone.runTask @ zone.js:151ZoneTask.invoke @ zone.js:345data.args.(anonymous function) @ zone.js:1224
error_handler.js:50 EXCEPTION: Cannot read property 'add_rule' of undefinedErrorHandler.handleError @ error_handler.js:50next @ application_ref.js:346schedulerFn @ async.js:91SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:77NgZone.triggerError @ ng_zone.js:329onHandleError @ ng_zone.js:290ZoneDelegate.handleError @ zone.js:246Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:345data.args.(anonymous function) @ zone.js:1224
error_handler.js:55 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:55next @ application_ref.js:346schedulerFn @ async.js:91SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:77NgZone.triggerError @ ng_zone.js:329onHandleError @ ng_zone.js:290ZoneDelegate.handleError @ zone.js:246Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:345data.args.(anonymous function) @ zone.js:1224
error_handler.js:56 TypeError: Cannot read property 'add_rule' of undefined
    at Object.eval [as group] (eval at d.template (eval at webpackJsonp.145.module.exports (http://localhost:4200/scripts.bundle.js:1:1)), <anonymous>:3:344)
    at g.getGroupTemplate (eval at webpackJsonp.145.module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:7:4585)
    at g.setRoot (eval at webpackJsonp.145.module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:6:16340)
    at new g (eval at webpackJsonp.145.module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:6:6795)
    at r.fn.init.$.fn.queryBuilder (eval at webpackJsonp.145.module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:7:12735)
    at QueryBuilderComponent.webpackJsonp.964.QueryBuilderComponent.initQueryBuilder (http://localhost:4200/main.bundle.js:9756:56)
    at HTMLDocument.<anonymous> (http://localhost:4200/main.bundle.js:9750:16)
    at j (eval at webpackJsonp.145.module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:2:29999)
    at k (eval at webpackJsonp.145.module.exports (http://localhost:4200/scripts.bundle.js:1:1), <anonymous>:2:30313)
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:150816:35)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:34841:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:150815:40)
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:150692:47)
    at ZoneTask.invoke (http://localhost:4200/vendor.bundle.js:150886:33)
    at data.args.(anonymous function) (http://localhost:4200/vendor.bundle.js:151765:25)
```

Any help or suggestion will be appreciated

**Comment by mistic100** [comment]
God those ugly stack traces with Zone.js in the way...

It looks like a problem while parsing the templates. Can you setup a small plunker with minimal config that reproduces the problem ?

**Comment by benzid-wael** [comment]
Below the configuration

```javascript
{
    allow_groups: false,
    allow_empty: true,
    lang_code: 'en',
    conditions: ['AND', 'OR'],
    default_condition: 'AND',
    icons: {
      'add_rule': '',
      'remove_rule': 'glyphicon glyphicon-trash'
    },
    operators: QueryBuilder.OPERATORS,
    templates: {
      'group': '\
        <dl id="{{= it.group_id }}" class="rules-group-container"> \
          <dt class="rules-group-header"> \
            <div class="btn-group pull-right group-actions"> \
              <!-- button type="button" class="add-rule-btn btn btn-xs btn-default" data-add="rule"> \
                <i class="{{= it.icons.add_rule }}"></i> {{= it.lang.add_rule }} \
              </button--> \
              {{? it.settings.allow_groups===-1 || it.settings.allow_groups>=it.level }} \
                <button type="button" class="btn btn-xs btn-default" data-add="group"> \
                  <i class="{{= it.icons.add_group }}"></i> {{= it.lang.add_group }} \
                </button> \
              {{?}} \
              {{? it.level>1 }} \
                <button type="button" class="btn btn-xs btn-danger" data-delete="group"> \
                  <i class="{{= it.icons.remove_group }}"></i> {{= it.lang.delete_group }} \
                </button> \
              {{?}} \
            </div> \
            <div class="btn-group group-conditions"> \
            </div> \
            {{? it.settings.display_errors }} \
              <div class="error-container"><i class="{{= it.icons.error }}"></i></div> \
            {{?}} \
          </dt> \
          <dd class=rules-group-body> \
            <ul class=rules-list></ul> \
          </dd> \
          \
          <div class="btn-group pull-left group-actions"> \
            <button type="button" class="add-rule-btn btn btn-xs btn-default" data-add="rule"> \
              <i class="{{= it.icons.add_rule }}"></i> {{= it.lang.add_rule }} \
            </button> \
          </div> \
        </dl>',
    }
  }
```

Note that the same code work when I include the library in `index.html`

**Comment by mistic100** [comment]
The templates changed a little bit in 2.4.2, "lang" is not exposed anymore but there is a "translate" function.
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/template.js#L6
