### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by felipecaparelli** [mistic100/jQuery-QueryBuilder#975]
**Error during component construction**

When the component is reading the rules data, it fails with the following error:

```
TypeError: Cannot read properties of undefined (reading 'id')
    at Rule.Node (query-builder.standalone.js:3694:22)
    at new Rule (query-builder.standalone.js:4060:10)
    at Group.addRule (query-builder.standalone.js:3951:28)
    at QueryBuilder.addRule (query-builder.standalone.js:1376:24)
    at query-builder.standalone.js:2231:30
    at Array.forEach (<anonymous>)
    at add (query-builder.standalone.js:2203:20)
    at QueryBuilder.setRules (query-builder.standalone.js:2283:6)
    at QueryBuilder.init (query-builder.standalone.js:853:14)
    at $.fn.queryBuilder (query-builder.standalone.js:4153:17)
```

- The data has not been changed. Follow the example:

```
{
	"condition":"OR",
	"rules":[
	{"id":"CUSTOMER.ACCOUNT_STATUS","field":"CUSTOMER.ACCOUNT_STATUS","type":"string","input":"text","operator":"equal","value":"Active"},
	{"id":"CUSTOMER.ACCOUNT_STATUS","field":"CUSTOMER.ACCOUNT_STATUS","type":"string","input":"text","operator":"equal","value":"New"}
	]
}
```

- Maybe the problem starts in the following line, as we don't have the attribute data inside the rule item:

`model = self.addRule(group, item.data, self.parseRuleFlags(item));`

But what is really causing the component to fail, is that inside the function setRoot(addRule, data, flags), the parsing to get the elements is returning a text node:

![queryBuilder_issue_06-29-2023](https://github.com/mistic100/jQuery-QueryBuilder/assets/1261351/c568529a-44f1-45d9-a6bd-552fc7f98325)

The code returning this empty node is `$($.parseHTML(this.getGroupTemplate(group_id, 1)));`

![queryBuilder_issue2_06-29-2023](https://github.com/mistic100/jQuery-QueryBuilder/assets/1261351/eb2f2b55-7223-47f9-a9f7-d69976ed797d)

And follow below the JSON generated to build the component:

```
{
	"plugins":{"bb-datepicker":{"format":"MM/dd/yyyy"},"bb-in-collection":null,"sortable":{"icon":"grip-handle"}},
	"filters":[
		{"id":"DECISION.ALWAYS_FALSE","label":"DECISION.ALWAYS_FALSE","type":"boolean","input":"radio","operators":["equal"],"values":[{"true":"True"},{"false":"False"}],"operandType":"DECISION"},
		{"id":"DECISION.ALWAYS_TRUE","label":"DECISION.ALWAYS_TRUE","type":"boolean","input":"radio","operators":["equal"],"values":[{"true":"True"},{"false":"False"}],"operandType":"DECISION"}
		],
	"rules":{"condition":"OR","rules":[{"id":"CUSTOMER.ACCOUNT_STATUS","field":"CUSTOMER.ACCOUNT_STATUS","type":"string","input":"text","operator":"equal","value":"Active"},{"id":"CUSTOMER.ACCOUNT_STATUS","field":"CUSTOMER.ACCOUNT_STATUS","type":"string","input":"text","operator":"equal","value":"Change_Of_Service"}]},"templates":{"filterSelect":"                            {{ var optgroup = null; }}                             <div class=\\"rule-filter-wrapper\\" ng-click=\\"vmEditor.openDecisionExprOperandSelection('{{= it.rule.id }}', $event)\\">                                 <input class=\\"form-control\\" name=\\"{{= it.rule.id }}_filter\\" type=\\"text\\">                                 <img class=\\"decision-hamburger\\" src=\\"img/decision-hamburger.svg\\"></i>                             </div>"},
	"display_errors":false
}
```

In the meantime, is there any way for me to override this function to avoid waiting for this fix (if this is really a bug)? Thanks

**Comment by felipecaparelli** [comment]
This issue is only occurring in the version 2.6.2, but is working fine in the version 2.5.2
